name: SonarCloud

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    uses: swissgrc/.github/.github/workflows/sonarcloud.yml@d91ad165227a6fecc01ede93fd6568bd32522455 # main
    secrets:
      gh-token: ${{ secrets.GITHUB_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
